### ISSUE TITLE
PHP Strict Warning

### ISSUE THREAD

**Issue by tilhom** [hreitsma/yii2-simplemath-captcha#1]
I install yii2-simplemath-captcha into basic app 2.0.8, but my app does not work

PHP Strict Warning – yii\base\ErrorException

Declaration of hr\captcha\CaptchaAction::validate() should be compatible with yii\captcha\CaptchaAction::validate($input, $caseSensitive)

**Comment by hreitsma** [comment]
Thank you for your message, I have added the second parameter to validate which should resolve the warning. Be sure to add the rules in the readme to your config/web.php even if you don't use prettyUrl.
