### ISSUE TITLE
Error when working with modules.

### ISSUE THREAD

**Issue by mmorejon** [hreitsma/yii2-simplemath-captcha#2]
The extension works perfect on contact page, but when I'm trying to setup for a module controller doesn't work correctly. I do click on the captcha image, but the input text validator doesn't refresh. Any suggestion?

**Comment by hreitsma** [comment]
No error, just like the default captcha wouldn't work without a custom url (captchaAction parameter):

`echo $form->field($contact, 'verifyCode')->widget(Captcha::className(), [
			'captchaAction' => '/your_module/your_controller/captcha',
			'template' => '<div class="row"><div class="col-lg-2">{image}</div><div class="col-lg-10">{input}</div></div>',
		])->hint('Hint: click on the equation to refresh');`
